This is an exploratory analysis of diabetes data. We start with our needed imports

In [3]:
import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

from collections import Counter

Now we must import our data into Pandas for processing.

In [5]:
df = pd.read_csv('diabetes.csv', encoding='latin1')

pd.set_option('display.max_columns', None) # Avoid truncation

Preliminary data exploration.

In [7]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

We don't have any unnecessary columns in our dataframe, and we don't see any signs of NaN values to be imputed. However, it is unclear as to what 0 or 1 mean for the Outcome column.